// Generated by delombok at Mon Apr 01 15:56:10 UTC 2024
package gov.cms.fiss.pricers.opps.core;

import gov.cms.fiss.pricers.common.application.rules.CalculationContext;
import gov.cms.fiss.pricers.opps.api.v2.IoceServiceLineData;
import gov.cms.fiss.pricers.opps.api.v2.ServiceLinePaymentData;
import gov.cms.fiss.pricers.opps.core.codes.ReturnCode;

/**
 * Context for processing individual service lines.
 */
public class ServiceLineContext extends CalculationContext<IoceServiceLineData, ServiceLinePaymentData> {
  private final OppsPricerContext pricerContext;

  public ServiceLineContext(OppsPricerContext pricerContext, IoceServiceLineData input, ServiceLinePaymentData output) {
    super(input, output);
    this.pricerContext = pricerContext;
  }

  /**
   * Updates the line return code value for the corresponding output line.
   */
  public void applyLineReturnCode(ReturnCode returnCode) {
    getOutput().setReturnCode(returnCode.toReturnCodeData());
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public OppsPricerContext getPricerContext() {
    return this.pricerContext;
  }
}
