// Generated by delombok at Mon Apr 01 15:56:10 UTC 2024
package gov.cms.fiss.pricers.opps.core.model;

import gov.cms.fiss.pricers.common.util.BigDecimalUtils;
import java.math.BigDecimal;

public class APCCalculationData {
  /**
   * Corresponds to {@code H-RANK PIC 9(05)} from the COBOL source.
   */
  private Integer rank = 0;
  /**
   * Corresponds to {@code H-MIN-COIN PIC 9(05)V9(02)} from the COBOL source.
   */
  private BigDecimal minimumCoinsurance = BigDecimalUtils.ZERO;
  /**
   * Corresponds to {@code H-NAT-COIN PIC 9(07)V9(02)} from the COBOL source.
   */
  private BigDecimal nationalCoinsurance = BigDecimalUtils.ZERO;
  /**
   * Corresponds to {@code H-PPCT PIC S9V9(06) COMP-3} from the COBOL source.
   */
  private BigDecimal rate = BigDecimalUtils.ZERO;

  /**
   * Corresponds to {@code H-RANK PIC 9(05)} from the COBOL source.
   */
  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public Integer getRank() {
    return this.rank;
  }

  /**
   * Corresponds to {@code H-MIN-COIN PIC 9(05)V9(02)} from the COBOL source.
   */
  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public BigDecimal getMinimumCoinsurance() {
    return this.minimumCoinsurance;
  }

  /**
   * Corresponds to {@code H-NAT-COIN PIC 9(07)V9(02)} from the COBOL source.
   */
  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public BigDecimal getNationalCoinsurance() {
    return this.nationalCoinsurance;
  }

  /**
   * Corresponds to {@code H-PPCT PIC S9V9(06) COMP-3} from the COBOL source.
   */
  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public BigDecimal getRate() {
    return this.rate;
  }

  /**
   * Corresponds to {@code H-RANK PIC 9(05)} from the COBOL source.
   */
  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public void setRank(final Integer rank) {
    this.rank = rank;
  }

  /**
   * Corresponds to {@code H-MIN-COIN PIC 9(05)V9(02)} from the COBOL source.
   */
  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public void setMinimumCoinsurance(final BigDecimal minimumCoinsurance) {
    this.minimumCoinsurance = minimumCoinsurance;
  }

  /**
   * Corresponds to {@code H-NAT-COIN PIC 9(07)V9(02)} from the COBOL source.
   */
  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public void setNationalCoinsurance(final BigDecimal nationalCoinsurance) {
    this.nationalCoinsurance = nationalCoinsurance;
  }

  /**
   * Corresponds to {@code H-PPCT PIC S9V9(06) COMP-3} from the COBOL source.
   */
  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public void setRate(final BigDecimal rate) {
    this.rate = rate;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public boolean equals(final java.lang.Object o) {
    if (o == this) return true;
    if (!(o instanceof APCCalculationData)) return false;
    final APCCalculationData other = (APCCalculationData) o;
    if (!other.canEqual((java.lang.Object) this)) return false;
    final java.lang.Object this$rank = this.getRank();
    final java.lang.Object other$rank = other.getRank();
    if (this$rank == null ? other$rank != null : !this$rank.equals(other$rank)) return false;
    final java.lang.Object this$minimumCoinsurance = this.getMinimumCoinsurance();
    final java.lang.Object other$minimumCoinsurance = other.getMinimumCoinsurance();
    if (this$minimumCoinsurance == null ? other$minimumCoinsurance != null : !this$minimumCoinsurance.equals(other$minimumCoinsurance)) return false;
    final java.lang.Object this$nationalCoinsurance = this.getNationalCoinsurance();
    final java.lang.Object other$nationalCoinsurance = other.getNationalCoinsurance();
    if (this$nationalCoinsurance == null ? other$nationalCoinsurance != null : !this$nationalCoinsurance.equals(other$nationalCoinsurance)) return false;
    final java.lang.Object this$rate = this.getRate();
    final java.lang.Object other$rate = other.getRate();
    if (this$rate == null ? other$rate != null : !this$rate.equals(other$rate)) return false;
    return true;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  protected boolean canEqual(final java.lang.Object other) {
    return other instanceof APCCalculationData;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    final java.lang.Object $rank = this.getRank();
    result = result * PRIME + ($rank == null ? 43 : $rank.hashCode());
    final java.lang.Object $minimumCoinsurance = this.getMinimumCoinsurance();
    result = result * PRIME + ($minimumCoinsurance == null ? 43 : $minimumCoinsurance.hashCode());
    final java.lang.Object $nationalCoinsurance = this.getNationalCoinsurance();
    result = result * PRIME + ($nationalCoinsurance == null ? 43 : $nationalCoinsurance.hashCode());
    final java.lang.Object $rate = this.getRate();
    result = result * PRIME + ($rate == null ? 43 : $rate.hashCode());
    return result;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public java.lang.String toString() {
    return "APCCalculationData(rank=" + this.getRank() + ", minimumCoinsurance=" + this.getMinimumCoinsurance() + ", nationalCoinsurance=" + this.getNationalCoinsurance() + ", rate=" + this.getRate() + ")";
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public APCCalculationData() {
  }
}
