// Generated by delombok at Mon Apr 01 15:56:10 UTC 2024
package gov.cms.fiss.pricers.opps.core.model;

import java.math.BigDecimal;

public class DeviceCreditInfo {
  private BigDecimal claimDeviceCreditAmount;
  private BigDecimal totalDeviceCreditPayments;
  private BigDecimal totalTerminatedProcedureDeviceOffsetPayments;
  private BigDecimal inpatientDeductibleLimit;

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public BigDecimal getClaimDeviceCreditAmount() {
    return this.claimDeviceCreditAmount;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public BigDecimal getTotalDeviceCreditPayments() {
    return this.totalDeviceCreditPayments;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public BigDecimal getTotalTerminatedProcedureDeviceOffsetPayments() {
    return this.totalTerminatedProcedureDeviceOffsetPayments;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public BigDecimal getInpatientDeductibleLimit() {
    return this.inpatientDeductibleLimit;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public void setClaimDeviceCreditAmount(final BigDecimal claimDeviceCreditAmount) {
    this.claimDeviceCreditAmount = claimDeviceCreditAmount;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public void setTotalDeviceCreditPayments(final BigDecimal totalDeviceCreditPayments) {
    this.totalDeviceCreditPayments = totalDeviceCreditPayments;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public void setTotalTerminatedProcedureDeviceOffsetPayments(final BigDecimal totalTerminatedProcedureDeviceOffsetPayments) {
    this.totalTerminatedProcedureDeviceOffsetPayments = totalTerminatedProcedureDeviceOffsetPayments;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public void setInpatientDeductibleLimit(final BigDecimal inpatientDeductibleLimit) {
    this.inpatientDeductibleLimit = inpatientDeductibleLimit;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public boolean equals(final java.lang.Object o) {
    if (o == this) return true;
    if (!(o instanceof DeviceCreditInfo)) return false;
    final DeviceCreditInfo other = (DeviceCreditInfo) o;
    if (!other.canEqual((java.lang.Object) this)) return false;
    final java.lang.Object this$claimDeviceCreditAmount = this.getClaimDeviceCreditAmount();
    final java.lang.Object other$claimDeviceCreditAmount = other.getClaimDeviceCreditAmount();
    if (this$claimDeviceCreditAmount == null ? other$claimDeviceCreditAmount != null : !this$claimDeviceCreditAmount.equals(other$claimDeviceCreditAmount)) return false;
    final java.lang.Object this$totalDeviceCreditPayments = this.getTotalDeviceCreditPayments();
    final java.lang.Object other$totalDeviceCreditPayments = other.getTotalDeviceCreditPayments();
    if (this$totalDeviceCreditPayments == null ? other$totalDeviceCreditPayments != null : !this$totalDeviceCreditPayments.equals(other$totalDeviceCreditPayments)) return false;
    final java.lang.Object this$totalTerminatedProcedureDeviceOffsetPayments = this.getTotalTerminatedProcedureDeviceOffsetPayments();
    final java.lang.Object other$totalTerminatedProcedureDeviceOffsetPayments = other.getTotalTerminatedProcedureDeviceOffsetPayments();
    if (this$totalTerminatedProcedureDeviceOffsetPayments == null ? other$totalTerminatedProcedureDeviceOffsetPayments != null : !this$totalTerminatedProcedureDeviceOffsetPayments.equals(other$totalTerminatedProcedureDeviceOffsetPayments)) return false;
    final java.lang.Object this$inpatientDeductibleLimit = this.getInpatientDeductibleLimit();
    final java.lang.Object other$inpatientDeductibleLimit = other.getInpatientDeductibleLimit();
    if (this$inpatientDeductibleLimit == null ? other$inpatientDeductibleLimit != null : !this$inpatientDeductibleLimit.equals(other$inpatientDeductibleLimit)) return false;
    return true;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  protected boolean canEqual(final java.lang.Object other) {
    return other instanceof DeviceCreditInfo;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    final java.lang.Object $claimDeviceCreditAmount = this.getClaimDeviceCreditAmount();
    result = result * PRIME + ($claimDeviceCreditAmount == null ? 43 : $claimDeviceCreditAmount.hashCode());
    final java.lang.Object $totalDeviceCreditPayments = this.getTotalDeviceCreditPayments();
    result = result * PRIME + ($totalDeviceCreditPayments == null ? 43 : $totalDeviceCreditPayments.hashCode());
    final java.lang.Object $totalTerminatedProcedureDeviceOffsetPayments = this.getTotalTerminatedProcedureDeviceOffsetPayments();
    result = result * PRIME + ($totalTerminatedProcedureDeviceOffsetPayments == null ? 43 : $totalTerminatedProcedureDeviceOffsetPayments.hashCode());
    final java.lang.Object $inpatientDeductibleLimit = this.getInpatientDeductibleLimit();
    result = result * PRIME + ($inpatientDeductibleLimit == null ? 43 : $inpatientDeductibleLimit.hashCode());
    return result;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public java.lang.String toString() {
    return "DeviceCreditInfo(claimDeviceCreditAmount=" + this.getClaimDeviceCreditAmount() + ", totalDeviceCreditPayments=" + this.getTotalDeviceCreditPayments() + ", totalTerminatedProcedureDeviceOffsetPayments=" + this.getTotalTerminatedProcedureDeviceOffsetPayments() + ", inpatientDeductibleLimit=" + this.getInpatientDeductibleLimit() + ")";
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public DeviceCreditInfo(final BigDecimal claimDeviceCreditAmount, final BigDecimal totalDeviceCreditPayments, final BigDecimal totalTerminatedProcedureDeviceOffsetPayments, final BigDecimal inpatientDeductibleLimit) {
    this.claimDeviceCreditAmount = claimDeviceCreditAmount;
    this.totalDeviceCreditPayments = totalDeviceCreditPayments;
    this.totalTerminatedProcedureDeviceOffsetPayments = totalTerminatedProcedureDeviceOffsetPayments;
    this.inpatientDeductibleLimit = inpatientDeductibleLimit;
  }
}
