// Generated by delombok at Mon Apr 01 15:56:10 UTC 2024
package gov.cms.fiss.pricers.opps.core.model;

import java.math.BigDecimal;

public class DevicePassThroughInfo {
  private BigDecimal totalQn;
  private BigDecimal wageAdjustedQn;
  private BigDecimal totalQo;
  private BigDecimal wageAdjustedQo;

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public BigDecimal getTotalQn() {
    return this.totalQn;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public BigDecimal getWageAdjustedQn() {
    return this.wageAdjustedQn;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public BigDecimal getTotalQo() {
    return this.totalQo;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public BigDecimal getWageAdjustedQo() {
    return this.wageAdjustedQo;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public void setTotalQn(final BigDecimal totalQn) {
    this.totalQn = totalQn;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public void setWageAdjustedQn(final BigDecimal wageAdjustedQn) {
    this.wageAdjustedQn = wageAdjustedQn;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public void setTotalQo(final BigDecimal totalQo) {
    this.totalQo = totalQo;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public void setWageAdjustedQo(final BigDecimal wageAdjustedQo) {
    this.wageAdjustedQo = wageAdjustedQo;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public boolean equals(final java.lang.Object o) {
    if (o == this) return true;
    if (!(o instanceof DevicePassThroughInfo)) return false;
    final DevicePassThroughInfo other = (DevicePassThroughInfo) o;
    if (!other.canEqual((java.lang.Object) this)) return false;
    final java.lang.Object this$totalQn = this.getTotalQn();
    final java.lang.Object other$totalQn = other.getTotalQn();
    if (this$totalQn == null ? other$totalQn != null : !this$totalQn.equals(other$totalQn)) return false;
    final java.lang.Object this$wageAdjustedQn = this.getWageAdjustedQn();
    final java.lang.Object other$wageAdjustedQn = other.getWageAdjustedQn();
    if (this$wageAdjustedQn == null ? other$wageAdjustedQn != null : !this$wageAdjustedQn.equals(other$wageAdjustedQn)) return false;
    final java.lang.Object this$totalQo = this.getTotalQo();
    final java.lang.Object other$totalQo = other.getTotalQo();
    if (this$totalQo == null ? other$totalQo != null : !this$totalQo.equals(other$totalQo)) return false;
    final java.lang.Object this$wageAdjustedQo = this.getWageAdjustedQo();
    final java.lang.Object other$wageAdjustedQo = other.getWageAdjustedQo();
    if (this$wageAdjustedQo == null ? other$wageAdjustedQo != null : !this$wageAdjustedQo.equals(other$wageAdjustedQo)) return false;
    return true;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  protected boolean canEqual(final java.lang.Object other) {
    return other instanceof DevicePassThroughInfo;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    final java.lang.Object $totalQn = this.getTotalQn();
    result = result * PRIME + ($totalQn == null ? 43 : $totalQn.hashCode());
    final java.lang.Object $wageAdjustedQn = this.getWageAdjustedQn();
    result = result * PRIME + ($wageAdjustedQn == null ? 43 : $wageAdjustedQn.hashCode());
    final java.lang.Object $totalQo = this.getTotalQo();
    result = result * PRIME + ($totalQo == null ? 43 : $totalQo.hashCode());
    final java.lang.Object $wageAdjustedQo = this.getWageAdjustedQo();
    result = result * PRIME + ($wageAdjustedQo == null ? 43 : $wageAdjustedQo.hashCode());
    return result;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public java.lang.String toString() {
    return "DevicePassThroughInfo(totalQn=" + this.getTotalQn() + ", wageAdjustedQn=" + this.getWageAdjustedQn() + ", totalQo=" + this.getTotalQo() + ", wageAdjustedQo=" + this.getWageAdjustedQo() + ")";
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public DevicePassThroughInfo(final BigDecimal totalQn, final BigDecimal wageAdjustedQn, final BigDecimal totalQo, final BigDecimal wageAdjustedQo) {
    this.totalQn = totalQn;
    this.wageAdjustedQn = wageAdjustedQn;
    this.totalQo = totalQo;
    this.wageAdjustedQo = wageAdjustedQo;
  }
}
