// Generated by delombok at Mon Apr 01 15:56:10 UTC 2024
package gov.cms.fiss.pricers.opps.core;

import gov.cms.fiss.pricers.common.application.rules.CalculationContext;
import gov.cms.fiss.pricers.opps.core.model.CoinsuranceCapEntry;
import gov.cms.fiss.pricers.opps.core.model.CoinsuranceCapValues;

public class CoinsuranceCapContext extends CalculationContext<CoinsuranceCapEntry, CoinsuranceCapValues> {
  private final OppsPricerContext pricerContext;

  public CoinsuranceCapContext(CoinsuranceCapEntry input, CoinsuranceCapValues output, OppsPricerContext pricerContext) {
    super(input, output);
    this.pricerContext = pricerContext;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public OppsPricerContext getPricerContext() {
    return this.pricerContext;
  }
}
