// Generated by delombok at Mon Apr 01 15:56:10 UTC 2024
package gov.cms.fiss.pricers.opps.core.tables;

import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import gov.cms.fiss.pricers.opps.core.tables.BloodRankEntry.Fields;
import javax.annotation.concurrent.Immutable;
import javax.validation.constraints.Digits;
import javax.validation.constraints.Pattern;

/**
 * Model for the BLOODAPC CSV file.
 */
@Immutable
@JsonDeserialize(builder = BloodRankEntry.BloodRankEntryBuilder.class)
@JsonPropertyOrder({Fields.HCPCS_CODE, Fields.RANK})
public class BloodRankEntry {

  @JsonPOJOBuilder(withPrefix = "")
  public static class BloodRankEntryBuilder {
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private String hcpcsCode;
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private Integer rank;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    BloodRankEntryBuilder() {
    }

    /**
     * @return {@code this}.
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BloodRankEntry.BloodRankEntryBuilder hcpcsCode(final String hcpcsCode) {
      this.hcpcsCode = hcpcsCode;
      return this;
    }

    /**
     * @return {@code this}.
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BloodRankEntry.BloodRankEntryBuilder rank(final Integer rank) {
      this.rank = rank;
      return this;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BloodRankEntry build() {
      return new BloodRankEntry(this.hcpcsCode, this.rank);
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
      return "BloodRankEntry.BloodRankEntryBuilder(hcpcsCode=" + this.hcpcsCode + ", rank=" + this.rank + ")";
    }
  }

  @Pattern(regexp = "P\\d{4}")
  private final String hcpcsCode;
  @Digits(integer = 2, fraction = 0)
  private final Integer rank;

  public BloodRankEntryBuilder copyBuilder() {
    return BloodRankEntry.builder().hcpcsCode(getHcpcsCode()).rank(getRank());
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  BloodRankEntry(final String hcpcsCode, final Integer rank) {
    this.hcpcsCode = hcpcsCode;
    this.rank = rank;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public static BloodRankEntry.BloodRankEntryBuilder builder() {
    return new BloodRankEntry.BloodRankEntryBuilder();
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public String getHcpcsCode() {
    return this.hcpcsCode;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public Integer getRank() {
    return this.rank;
  }


  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public static final class Fields {
    public static final java.lang.String HCPCS_CODE = "hcpcsCode";
    public static final java.lang.String RANK = "rank";
  }
}
