// Generated by delombok at Mon Apr 01 15:56:10 UTC 2024
package gov.cms.fiss.pricers.opps.core.tables;

import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import gov.cms.fiss.pricers.opps.core.tables.PreviousYearWageIndexEntry.Fields;
import java.math.BigDecimal;
import javax.annotation.concurrent.Immutable;
import javax.validation.constraints.Digits;
import javax.validation.constraints.Size;

/**
 * Model for the OPPSWI2019 CSV file.
 */
@Immutable
@JsonDeserialize(builder = PreviousYearWageIndexEntry.PreviousYearWageIndexEntryBuilder.class)
@JsonPropertyOrder({Fields.PROVIDER_NUMBER, Fields.WAGE_INDEX})
public class PreviousYearWageIndexEntry {

  @JsonPOJOBuilder(withPrefix = "")
  public static class PreviousYearWageIndexEntryBuilder {
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private String providerNumber;
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private BigDecimal wageIndex;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    PreviousYearWageIndexEntryBuilder() {
    }

    /**
     * @return {@code this}.
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public PreviousYearWageIndexEntry.PreviousYearWageIndexEntryBuilder providerNumber(final String providerNumber) {
      this.providerNumber = providerNumber;
      return this;
    }

    /**
     * @return {@code this}.
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public PreviousYearWageIndexEntry.PreviousYearWageIndexEntryBuilder wageIndex(final BigDecimal wageIndex) {
      this.wageIndex = wageIndex;
      return this;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public PreviousYearWageIndexEntry build() {
      return new PreviousYearWageIndexEntry(this.providerNumber, this.wageIndex);
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
      return "PreviousYearWageIndexEntry.PreviousYearWageIndexEntryBuilder(providerNumber=" + this.providerNumber + ", wageIndex=" + this.wageIndex + ")";
    }
  }

  @Size(min = 6, max = 6)
  private final String providerNumber;
  @Digits(integer = 2, fraction = 4)
  private final BigDecimal wageIndex;

  public PreviousYearWageIndexEntryBuilder copyBuilder() {
    return PreviousYearWageIndexEntry.builder().providerNumber(getProviderNumber()).wageIndex(getWageIndex());
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  PreviousYearWageIndexEntry(final String providerNumber, final BigDecimal wageIndex) {
    this.providerNumber = providerNumber;
    this.wageIndex = wageIndex;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public static PreviousYearWageIndexEntry.PreviousYearWageIndexEntryBuilder builder() {
    return new PreviousYearWageIndexEntry.PreviousYearWageIndexEntryBuilder();
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public String getProviderNumber() {
    return this.providerNumber;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public BigDecimal getWageIndex() {
    return this.wageIndex;
  }


  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public static final class Fields {
    public static final java.lang.String PROVIDER_NUMBER = "providerNumber";
    public static final java.lang.String WAGE_INDEX = "wageIndex";
  }
}
