// Generated by delombok at Mon Apr 01 15:56:10 UTC 2024
package gov.cms.fiss.pricers.opps.core.codes;

import org.apache.commons.lang3.StringUtils;

public enum ActionFlag {
  /**
   * Line item denial or rejection is not ignored.
   */
  LINE_ITEM_DENIAL_OR_REJECTION_IS_NOT_IGNORED_0("0"), /**
   * Line item denial or rejection is ignored.
   */
  LINE_ITEM_DENIAL_OR_REJECTION_IS_IGNORED_1("1"), /**
   * External line item denial. Line item is denied even if no IOCE edits are present.
   */
  EXTERNAL_LINE_ITEM_DENIAL_2("2"), /**
   * External line item rejection. Line item is rejected even if no IOCE edits are present.
   */
  EXTERNAL_LINE_ITEM_REJECTION_3("3"), /**
   * External line item adjustment. Technical charge rules apply.
   */
  EXTERNAL_LINE_ITEM_ADJUSTMENT_4("4");
  private final String flag;

  ActionFlag(String flag) {
    this.flag = flag;
  }

  public boolean is(String actionFlag) {
    return StringUtils.equals(flag, actionFlag);
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public String getFlag() {
    return this.flag;
  }
}
